### PR TITLE
Neglect covar

### PR DESCRIPTION
**Pull request by phillipstanleymarbell**

### CODE REVIEW

**Comment by harrysarson** [comment]
I can fix the conflicts on monday if that would be helpful :)

**Comment by phillipstanleymarbell** [comment]
> I can fix the conflicts on monday if that would be helpful :)

Yes, thanks!

**Comment by harrysarson** [comment]
I have been focusing my attention over at https://github.com/phillipstanleymarbell/Sunflower-toolchain/pull/18. I will take a look here next 🙂

**Comment by SamuelmsWong** [comment]
@harrysarson said to use his uncertain branch instead. Should we remove this PR?

**Comment by SamuelmsWong** [comment]
I will remove this PR and create one for Harry's uncertain branch

**Comment by harrysarson** [comment]
The new PR was #110

**Pull request closed without merging**
